"""
fieldline_tracer.py

Post-processing and visualization utilities for combining magnetic field
solutions from inner and outer Non-Spherical Potential Field (NSPF) domains.

This module provides helper functions to trace, merge, and visualize magnetic
field lines obtained from finite-element NSPF solutions stored in VTK format.
In particular, it supports:
- Tracing field lines in the inner domain from various seed surfaces
  (e.g., spherical shells, circular arcs, or arbitrary seed meshes).
- Identifying field-line intersections with the source surface (SS).
- Continuing field-line tracing into an outer potential-field domain.
- Merging inner and outer field-line segments into continuous magnetic field lines.
- Optional slice-based visualization of the resulting field lines and magnetic
  field magnitude.

The functions in this module operate on VTK meshes generated by the NSPF models,
and rely on PyVista for streamline tracing and geometric operations. They are
intended for analysis and visualization purposes only, and do not modify or
solve the underlying physical model.

Typical use cases include:
- Connecting magnetic field lines across the source surface to visualize
  open and closed magnetic structures.
- Tracing field lines from the photosphere to the outer boundary for comparison
  with coronal observations.
- Producing diagnostic figures for NSPF simulations presented in the
  accompanying publication.

This code is used in:
Wu et al. (2026), ApJS, submitted.

Author: Ziqi Wu
"""


import numpy as np
import pyvista as pv
pv.global_theme.allow_empty_mesh = True

def combine_in_out(result_path, inner_result_name, outer_result_name,
                   ss_path, ss_name,
                   plot_slice=False,slice_normal='z',slice_origin=[0,0,0]):
    """
    Combine magnetic field lines traced from inner and outer NSPF solutions.

    This function traces magnetic field lines in the inner domain, identifies
    field lines that intersect the source surface (SS), and continues their
    tracing into the outer domain. Inner and outer segments are merged to form
    continuous magnetic field lines across the source surface.

    The resulting field lines can optionally be visualized together with
    slice plots of the magnetic field magnitude.

    Parameters
    ----------
    result_path : str
        Directory containing the VTK files of the NSPF solutions.
    inner_result_name : str
        File name (without extension) of the inner-domain NSPF solution.
    outer_result_name : str
        File name (without extension) of the outer-domain NSPF solution.
    ss_path : str
        Directory containing the source surface (SS) mesh.
    ss_name : str
        File name (without extension) of the SS surface mesh (STL format).
    plot_slice : bool, optional
        If True, display a slice visualization of the merged field lines and
        magnetic field magnitude.
    slice_normal : str or array-like, optional
        Normal direction of the slicing plane used for visualization.
    slice_origin : array-like, optional
        Origin of the slicing plane

    Returns
    -------
    inner_Blines_slice : pyvista.PolyData
        Streamlines traced in the inner domain before merging.
    merged_Blines : list of pyvista.PolyData
        List of merged magnetic field lines, with inner and outer segments
        combined when applicable.
    inner_mesh_slice : pyvista.PolyData
        Slice of the inner-domain mesh used for visualization.
    """

    # --- Load NSPF inner and outer magnetic field solutions and SS surface ---
    inner_mesh = pv.read(result_path + inner_result_name + '.vtk')
    outer_mesh = pv.read(result_path + outer_result_name + '.vtk')
    ss_mesh = pv.read(ss_path + ss_name + '.stl')

    # --- Construct slice planes for visualization and streamline seeding ---
    ss_mesh_slice = ss_mesh.slice(normal=slice_normal, origin=slice_origin)
    inner_mesh_slice = inner_mesh.slice(normal=slice_normal, origin=slice_origin)

    # --- Generate multiple offset seed surfaces for dense streamline seeding
    # near the source surface (SS) ---

    ss_mesh_inner = ss_mesh.copy()
    r_ss_mesh_inner = np.linalg.norm(ss_mesh_inner.points, axis=1)

    ss_mesh_inner.points = ss_mesh_inner.points*(0.25/r_ss_mesh_inner[:,None] + 0.75)
    source_inner = ss_mesh_slice.merge(ss_mesh_inner.slice(normal=slice_normal, origin=slice_origin))

    ss_mesh_inner.points = ss_mesh_inner.points*(0.5/r_ss_mesh_inner[:,None] + 0.5)
    source_inner = source_inner.merge(ss_mesh_inner.slice(normal=slice_normal, origin=slice_origin))

    ss_mesh_inner.points = ss_mesh_inner.points*(0.75/r_ss_mesh_inner[:,None] + 0.25)
    source_inner = source_inner.merge(ss_mesh_inner.slice(normal=slice_normal, origin=slice_origin))

    # --- Trace magnetic field lines in the inner domain from SS-adjacent seeds ---
    inner_Blines_slice = inner_mesh.streamlines_from_source(source_inner, progress_bar=True, max_time=30)

    merged_Blines = []

    # --- Loop over individual field lines and identify SS-crossing candidates ---
    for i_line in range(inner_Blines_slice.n_cells):

        Bline = inner_Blines_slice.extract_cells(i_line)
        Bline_rs = np.linalg.norm(Bline.points, axis=1)
        #  Identify the apex (maximum radial distance) of the field line
        top_arg = np.nanargmax(Bline_rs)
        top_pt = Bline.points[top_arg]
        top_br = Bline['Br'][top_arg]
        top_bxyz = Bline['Bxyz'][top_arg]
        # Only attempt SS connection for field lines with significant radial
        # magnetic field at the apex
        if abs(top_br) > 1e-2:
            # Probe points along the local magnetic field direction
            steps = np.arange(-0.1, 0.1, 0.02)
            test_points = np.array([top_pt + step * top_bxyz / np.linalg.norm(top_bxyz) for step in steps])
            # Sort probe points radially outward
            test_points_r = np.linalg.norm(test_points,axis=1)
            test_points=test_points[test_points_r.argsort(),:]
            # Test whether any probe point exits the SS surface
            test_points_poly = pv.PolyData(test_points)
            selected = test_points_poly.select_enclosed_points(ss_mesh, inside_out=True)
            mask = np.array(selected['SelectedPoints'])
            print(mask)

            # If the field line crosses the SS, continue tracing
            # in the outer domain and merge inner and outer segments
            if any(mask == 1):
                ssfp_xyz = test_points[mask == 1][0]
                outer_Bline = outer_mesh.streamlines('Bxyz',start_position=ssfp_xyz, progress_bar=True, max_time=1000)
                # Ensure consistent polarity of Br across SS
                outer_Bline['Br'] = outer_Bline['Br'] * np.sign(top_br)
                # Sort inner and outer segments radially for concatenation
                Bline_sort_mask = np.argsort(Bline_rs)
                Bline_sort = Bline.points[Bline_sort_mask]
                outer_Bline_rs = np.linalg.norm(outer_Bline.points,axis=1)
                outer_Bline_sort_mask = np.argsort(outer_Bline_rs)
                outer_Bline_sort = outer_Bline.points[outer_Bline_sort_mask]
                # Concatenate inner and outer field-line segment
                new_line_pts = np.vstack([Bline_sort,outer_Bline_sort])
                new_line = pv.lines_from_points(new_line_pts)
                new_line['Br'] = np.hstack([Bline['Br'][Bline_sort_mask],outer_Bline['Br'][outer_Bline_sort_mask]])

                merged_Blines.append(new_line)
            # Closed field lines entirely within the inner domain
            else:
                merged_Blines.append(Bline)
        else:
            merged_Blines.append(Bline)

    # %% Optional visualization of magnetic field slices and merged field lines
    if plot_slice:

        p = pv.Plotter()
        for merged_bline in merged_Blines:
            p.add_mesh(merged_bline)
        p.add_mesh(inner_mesh_slice,scalars='Btot',opacity=0.4,cmap='jet',log_scale=True)
        p.show_axes()
        p.show_grid()
        p.show()

    return inner_Blines_slice, merged_Blines, inner_mesh_slice